### ISSUE TITLE
Anti-kik

### ISSUE THREAD

**Issue by CoolDEDXD** [IcyRelic/SpookSuite#13]
**Description**
Anti-kick
**Use Case**
A few minutes ago, the game was updated and the ability to kick players for the host was added, and now the search for the game has increased since often players just kick you, some kind of parry would be nice. I think it can be implemented

**Additional context**
And thank you for the work you've done, all of you, very fan-friendly gameplay with your menu)

**Comment by CoolDEDXD** [comment]
![Снимок экрана (1850)](https://github.com/IcyRelic/SpookSuite/assets/156037376/5fa55040-8681-468f-966e-fa688ee13a81)

**Comment by KomiiFN** [comment]
I agree I would love to see an anti-kick, in the near future, it would be an amazing addition.

**Comment by TheGreenBandit** [comment]
Already figured it out in the discord with holden, will be worked on tonight
