### ISSUE TITLE
[Bug] Join Random

### ISSUE THREAD

**Issue by TheGreenBandit** [IcyRelic/SpookSuite#14]
**Describe the bug**
When pressing join random you will get stuck in an inf loading screen

**SpookSuite Version:** latest
**Game Version:** latest

**Steps To Reproduce**
Press join random

**Screenshots**

**Additional context**

**Comment by MarkDragon420** [comment]
I've been getting around that using region setting mod and the debug in spook, seems to work for now cause the join with mods module isn't working at least for me.

**Comment by TheGreenBandit** [comment]
I put a "modal" in for now to fix it. Works fine
