### ISSUE TITLE
GodMode is invalid

### ISSUE THREAD

**Issue by laodediao** [IcyRelic/SpookSuite#16]
GodMode mode doesn't work, I deleted the configuration and even reinsta
![屏幕截图 2024-05-28 084620](https://github.com/IcyRelic/SpookSuite/assets/82866193/d9cbbeb5-c1b0-438a-babb-f10a6ddc4242)
lled the game, GodMode doesn't work.

**Comment by TheGreenBandit** [comment]
It does work, idk whats wrong as some people it does work some people it dont work

**Comment by TheGreenBandit** [comment]
It does work, idk whats wrong as some people it does work some people it dont work
