### ISSUE TITLE
Bug relating to unintended features while a menu option is open

### ISSUE THREAD

**Issue by Kyxlii** [IcyRelic/SpookSuite#17]
**Describe the bug**
When the "Self" menu option is open, the player enters a flying state until the menu option is changed or the menu is closed.

**SpookSuite Version:** v1.2.0
**Game Version:** 1.17.a

**Steps To Reproduce**
Enter the game, open the menu and enter the "Self" menu option using the top bar. Then jump. The player is in a state where they can jump in air and fall incredibly slowly. Movement speed is identical to walking/running.

**Screenshots**
[A short video showcasing the bug (streamable)](https://streamable.com/d2kzcr)

**Additional context**
This occurs in both solo and multiplayer lobbies.

**Comment by Civilux** [comment]
that has already been fixed in the latest commit

**Comment by Kyxlii** [comment]
Oh great I'll go build it now, thanks
