### ISSUE TITLE
Errors on building into a dll file - what do i do

### ISSUE THREAD

**Issue by fuckedd** [IcyRelic/SpookSuite#2]
can you help me on what the title says

**Comment by TheGreenBandit** [comment]
how so? provide context, what errors you get

**Comment by Unk88** [comment]
Having same problems building dll with namespaces 
![image_2024-05-07_034625337](https://github.com/IcyRelic/SpookSuite/assets/149540735/0ad04798-8dbe-4b21-b8eb-e6c9ac9bec2a)

**Comment by TheGreenBandit** [comment]
You have to add the dlls to reference lol, its telling you right there

**Comment by GFYI** [comment]
> You have to add the dlls to reference lol, its telling you right there

i tried that as well and it gave me more i'm not home right now i will see later and put what it says

**Comment by IcyRelic** [comment]
The dlls can be found in the game install folder for example

C:\Program Files (x86)\Steam\steamapps\common\Content Warning\Content Warning_Data\Managed

**Comment by Toaaa** [comment]
> > The dlls can be found in the game install folder for example
> > C:\Program Files (x86)\Steam\steamapps\common\Content Warning\Content Warning_Data\Managed
> 
> Which specific dlls do i add since i'm getting 400+ errors and i can't add every single dll

You want to copy every dll file from `\steamapps\common\Content Warning\Content Warning_Data\Managed\` to `SpookSuite\SpookSuite\Resources\`
