### ISSUE TITLE
Godmode

### ISSUE THREAD

**Issue by Aiko23211** [IcyRelic/SpookSuite#20]
**Describe the bug**
With god mode on you still take damage

**SpookSuite Version:** latest version
**Game Version:** latest version

**Steps To Reproduce**
Provide detailed steps to reproduce the bug.
open the GUI and press god mode then take damage

**Screenshots**

**Additional context**

**Comment by TheGreenBandit** [comment]
Is it to a specific enemy? Do you have a video of it happening?

**Comment by Aiko23211** [comment]
Its just in general to everything

**Comment by TheGreenBandit** [comment]
Will check it out when i get home from work

**Comment by TheGreenBandit** [comment]
alright seems to be an issue, will try and figure out what is wrong

**Comment by TheGreenBandit** [comment]
Fixed
