### ISSUE TITLE
[BUG] "Equip on Spawn" issue

### ISSUE THREAD

**Issue by OhsJol** [IcyRelic/SpookSuite#21]
**Describe the bug**
In the "Item" tab, "Equip on Spawn" doesn't work (Tested in "Play with friends")

**SpookSuite Version:** 1.2.0
**Game Version:** 1.18.c

**Steps To Reproduce**
Go to "Item" tab > Enable "Equip on Spawn" > Spawn any items

**Screenshots**
Every item here was spawned with "Equip on Spawn" enabled.
![image](https://github.com/user-attachments/assets/526f406a-0cb4-4a9d-9c03-56accb24b7c2)
On surface same
![image](https://github.com/user-attachments/assets/ee0ad97d-ea1c-4742-90d4-4e09a26a70f6)

**Additional context**
I don't think the other context needs

**Comment by TheGreenBandit** [comment]
valid issue, needa figure out where it isnt working

**Comment by TheGreenBandit** [comment]
should be fixed now
