### ISSUE TITLE
[BUG?] "Invisibility" fixed with patch

### ISSUE THREAD

**Issue by OhsJol** [IcyRelic/SpookSuite#22]
**Describe the bug**
New patch fixed this
![image](https://github.com/user-attachments/assets/4db467f0-7910-4350-8aac-5da041cdcab8)
"Invisibility" no longer works and players can see you even when "Invisibility" is active.

**SpookSuite Version:** 1.2.0
**Game Version:** 1.18.c

**Steps To Reproduce**
In "Self", enable "Invisibility > Ask the nearest player, "Can you see me?"

**Screenshots**
I have no friends to demonstrate this (no surprise there)

**Additional context**
I don't need to I guess

**Comment by TheGreenBandit** [comment]
fixed
