### ISSUE TITLE
[BUG] "No Ragdoll" does not work

### ISSUE THREAD

**Issue by OhsJol** [IcyRelic/SpookSuite#23]
**Describe the bug**
Сharacter will still ragdoll even if "No Ragdoll" is turned on.

**SpookSuite Version:** 1.2.0
**Game Version:** 1.18.c

**Steps To Reproduce**
Turn on "No Ragdoll" > Fall from a high place

**Screenshots**
*Videos
Falling in Old World (This FPS is wild)

https://github.com/user-attachments/assets/0076e17f-cc6a-402e-ac56-af701cba50b6

Falling in Upperworld/Home

https://github.com/user-attachments/assets/bf049fd4-8617-4d9a-a117-f0bd3f03e48a

**Additional context**
Idk

**Comment by TheGreenBandit** [comment]
Fixed
