### ISSUE TITLE
[Why I'm even writing this] "Kick all" does not work

### ISSUE THREAD

**Issue by OhsJol** [IcyRelic/SpookSuite#24]
**Describe the bug**
"Kick All" does not work. It's just a useless button

**SpookSuite Version:** 1.2.0
**Game Version:** 1.18.c

**Steps To Reproduce**
Open "Players" tab > Press "Kick All" Execute

**Screenshots**
*Video
(May be loud for some people)

https://github.com/user-attachments/assets/fd5353b9-d29a-4e9d-b5d6-53ec6a1eb21e

GET OUT

**Additional context**
I checked it as a host in the public lobby on this video

**Comment by TheGreenBandit** [comment]
Method that we use to kick all seems to actually have a function now, will have to find a workaround

**Comment by TheGreenBandit** [comment]
fixed
