### ISSUE TITLE
[BUG?] MetaCoins can't be removed

### ISSUE THREAD

**Issue by OhsJol** [IcyRelic/SpookSuite#25]
**Describe the bug**
MetaCoins can't be removed. It's just 0. 

**SpookSuite Version:** 1.2.0
**Game Version:** 1.18.c

**Steps To Reproduce**
Open "Misc" > Enter any number in "MetaCoins" and click "Remove"

**Screenshots**
*Video

https://github.com/user-attachments/assets/7823ba66-7aba-4b97-b017-06286cca1185

**Additional context**
Tested in "Play with friends". Outside the video has been tested with players

**Comment by TheGreenBandit** [comment]
Old version update your menu

**Comment by OhsJol** [comment]
Is there a new version of the menu? I don't see anything updated anywhere. Where is the new version published?

**Comment by TheGreenBandit** [comment]
> Is there a new version of the menu? I don't see anything updated anywhere. Where is the new version published?

Discord in general under the  content warning section
