### ISSUE TITLE
Players & Misc Tab is not working

### ISSUE THREAD

**Issue by PblBAKHello** [IcyRelic/SpookSuite#32]
**Describe the bug**

**SpookSuite Version:** [v1.2.0]
**Game Version:** [1.19e]

**Steps To Reproduce**
1. Open the menu
2. Click on the 'Players' or 'Misc' tab

**Screenshots**
![image](https://github.com/user-attachments/assets/4076872e-4745-485e-ad80-7ffed673f375)

UPD 1 - Not the player tab, item tab.

**Comment by TheGreenBandit** [comment]
Please update your menu by either building from source or downloading from the general channel in the discord.
