### ISSUE TITLE
Can you please provide a release version?

### ISSUE THREAD

**Issue by nspron** [IcyRelic/SpookSuite#6]
😊

**Comment by Toaaa** [comment]
Soon :D

**Comment by Civilux** [comment]
compiling yourself is always an option

**Comment by Toaaa** [comment]
I have compiled the latest version and uploaded it [here](https://pa.toaaa.de/ss/latest/SpookSuite-latest.zip). Feel free to download it. However, the best option is always to compile it yourself.
